language: node_js
node_js:
- node
script:
- npm run build
- npm run coverage
after_script:
- cat coverage/lcov.info | ./node_modules/.bin/coveralls
deploy:
  provider: npm
  email: hkclex@gmail.com
  api_key:
    secure: QAqPjTMCAZSmj6m8H0NoviGP9sunztlCFqVqgFOr3txYLLbIPbZuQzso3vpEBMw/sP8KdbSybjN6sL6QwQxAL1AwVOJYi3Jr7xifBOMus/hkkJWR+VpTJ3ClBYP7BcQfJjP3pGqU/Ci+kQwtU2wuujN8P68RME+yqOjxNmAPn7/jk3Yxbj7esAihnpMeM8H9La/iPBLfG1Lf2nIXZiRXLs1l6P0DsKcqFXpAxAsWNrNRNEsfXXFSIXGlTIGlPTgKSZSenccHyDpEXNfHmYfawMZI965+BSqiIEenqQXD/tPqk/0cIZzlEJXukN9K8MRg3PX409+Yqxp0px5fZ5TtUMbrCH8HoaCIR1XR3+lNBWEuYFi4SDo7guxx219rfOpk+tlgHOPR5eUk9Fub84tO5X+kXP5pj1vNAOaLCxwrbTnMpiyt+2edpkVjhNnecRcsDyaTJf0I32mXc0zOBB9aFFiSYy21ak38GcSaAGkTHIMR5kQ/o4AYd6+NsMVBsMB1d23rPKO0y7nkKCba5jUhS0k0F1KgyIYgSI5Qko0WC3HzLKDCM0JcPsoga8Rzto72owcxE6LNF4gSmZ4B0cvHXoApMe58a97NbcjY8xSflZoTxkajPHIb0EFGCnxMSFcSdWljbQOosc9Hq6uhWgAzaSvyr5xZZC2l6XmIERpsrU4=
  on:
    tags: true
    repo: darkcl/versionify
